server:
  port: 8090

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:49161/tp.local
    username: postgres
    password: q1w2e3r4
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
